version: "3.7"
services:
  app:
    image: louislam/uptime-kuma
    container_name: uptime-kuma
    volumes:
      - ./data:/app/data
    ports:
      - 3009:3001
    tty: true
    stdin_open: true

    restart: unless-stopped
